# Generated by Django 5.2.8 on 2025-11-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('business', 'Business'), ('finance', 'Finance & Accounting'), ('it_software', 'IT & Software'), ('office_productivity', 'Office Productivity'), ('personal_development', 'Personal Development'), ('design', 'Design'), ('marketing', 'Marketing'), ('lifestyle', 'Lifestyle'), ('photography_video', 'Photography & Video'), ('health_fitness', 'Health & Fitness'), ('music', 'Music'), ('teaching_academics', 'Teaching & Academics'), ('unknown', "I don't know yet")], max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('prerequisite', models.CharField(max_length=200)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('review', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to='course_thumbnails')),
                ('offer', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=30)),
                ('video', models.FileField(blank=True, null=True, upload_to='course_videos')),
                ('document', models.FileField(blank=True, null=True, upload_to='course_documents')),
            ],
        ),
    ]
