# Generated by Django 5.2.8 on 2025-11-21 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0003_alter_chapter_course_alter_module_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='Tutor.course'),
        ),
        migrations.AlterField(
            model_name='module',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='Tutor.chapter'),
        ),
    ]
