# Generated by Django 5.2.8 on 2025-11-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0004_alter_chapter_course_alter_module_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='review',
        ),
    ]
